let reports=[], position=null, miniMap, fullMap, boundaryData=null, boundaryLoad=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={token:sessionStorage.getItem('bw_token'),user:JSON.parse(sessionStorage.getItem('bw_user')||'null'),officers:[]};
const api=async(path,options={})=>{const headers={...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};const res=await fetch(`/api${path}`,{...options,headers:{...headers,...options.headers}});const data=await res.json().catch(()=>({message:'Unexpected server response.'}));if(!res.ok)throw new Error(data.message||'Request failed.');return data;};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4500)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function statusClass(s){return s.replace(' ','-')} function displayDate(value){return new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'});}
function switchView(id){if(id==='dashboard'&&!state.token)id='staffLogin';$$('.view').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='dashboard')renderDashboard().then(()=>setTimeout(initMaps,80)).catch(handleAuthError);}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#backCitizen').onclick=()=>switchView('home');
$('#locateBtn').onclick=()=>{if(!navigator.geolocation){toast('Location is not supported by this browser.');return}$('#locationLabel').textContent='Finding location…';navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude};$('#locationLabel').textContent='Location captured';$('#locationNote').textContent=`GPS captured: ${position.lat.toFixed(5)}, ${position.lng.toFixed(5)}`;},()=>{position={lat:-0.3031,lng:36.0800};$('#locationLabel').textContent='Sample location used';$('#locationNote').textContent='Location permission unavailable — a sample location is selected for this demo.';},{enableHighAccuracy:true,timeout:8000})};
$('#photo').onchange=e=>$('#photoLabel').textContent=e.target.files[0]?e.target.files[0].name.slice(0,16)+' ✓':'Add photo';
$('#contactConsent').onchange=e=>{const fields=$('#contactFields');fields.hidden=!e.target.checked;$('#contactEmail').required=e.target.checked&&!$('#contactPhone').value;$('#contactPhone').required=e.target.checked&&!$('#contactEmail').value;};
$('#reportForm').onsubmit=async e=>{e.preventDefault();if(!position){toast('Please capture your location before sending the report.');return}const form=new FormData();['category','severity','description','roadName','landmark','contactEmail','contactPhone'].forEach(k=>form.append(k,$('#'+k).value));form.append('contactConsent',$('#contactConsent').checked);form.append('latitude',position.lat);form.append('longitude',position.lng);if($('#photo').files[0])form.append('photo',$('#photo').files[0]);try{const {report}=await api('/reports',{method:'POST',body:form});$('#reportForm').reset();$('#contactFields').hidden=true;position=null;$('#locationLabel').textContent='Use my location';$('#photoLabel').textContent='Add photo';$('#locationNote').textContent=`Report ${report.reference} was routed to ${report.office}. Keep this reference to track updates.`;toast(`Report sent successfully. Reference: ${report.reference}`);}catch(error){toast(error.message);}};
$('#trackForm').onsubmit=async e=>{e.preventDefault();const target=$('#trackResult'),reference=$('#trackingId').value.trim().toUpperCase();if(!reference)return;try{const {report:r}=await api(`/reports/track/${encodeURIComponent(reference)}`);target.innerHTML=`<article class="track-card"><span class="status ${statusClass(r.status)}">${r.status}</span><h2>${escapeHtml(r.reference)} · ${escapeHtml(r.category)}</h2><p>${escapeHtml(r.description||'No further details provided.')}</p><p><strong>Road:</strong> ${escapeHtml(r.roadName||'Not specified')}<br><strong>Routed to:</strong> ${escapeHtml(r.office)}</p><small>Submitted ${displayDate(r.createdAt)} · ${r.repairPhotoCount} repair photo(s) attached</small></article>`;}catch(error){target.innerHTML=`<article class="track-card"><strong>Report unavailable</strong><p>${escapeHtml(error.message)}</p></article>`;}};
function setStaffControls(){const isAdmin=state.user?.role==='admin';$('#enrollmentNav').hidden=!isAdmin;$('#managementNav').hidden=!isAdmin;}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});state.token=data.token;state.user=data.user;sessionStorage.setItem('bw_token',data.token);sessionStorage.setItem('bw_user',JSON.stringify(data.user));$('#staffName').textContent=data.user.name;$('#staffRole').textContent=data.user.role;$('#staffOffice').textContent=data.user.office;setStaffControls();switchView('dashboard');}catch(error){$('#loginError').textContent=error.message;}};
function row(r,full=false){const icon=r.category==='Pothole'?'◉':'△',assignee=r.assignedTo?.name||'Unassigned';const update=`<select class="status-update" data-report-id="${r.id}" aria-label="Update ${escapeHtml(r.reference)}"><option ${r.status==='New'?'selected':''}>New</option><option ${r.status==='In progress'?'selected':''}>In progress</option><option ${r.status==='Resolved'?'selected':''}>Resolved</option></select>`;const assignment=['admin','coordinator'].includes(state.user?.role)?`<select class="assignment-update" data-report-id="${r.id}" aria-label="Assign ${escapeHtml(r.reference)}"><option value="">Unassigned</option>${state.officers.map(o=>`<option value="${o._id}" ${r.assignedTo?.id===o._id?'selected':''}>${escapeHtml(o.name)}</option>`).join('')}</select>`:'';const photoButton=r.reporterPhotoUrl?`<button class="text-button" data-action="citizen-photo" data-report-id="${r.id}">Citizen photo</button> `:'';return full?`<div class="full-report"><span class="report-icon">${icon}</span><div class="report-info"><strong>${escapeHtml(r.category)}</strong><small>${escapeHtml(r.reference)} · ${escapeHtml(r.office)} · ${displayDate(r.createdAt)}</small><span class="audit-note">${escapeHtml(r.severity)} priority · ${escapeHtml(assignee)} · ${r.comments} comment(s)</span></div><span class="severity">${photoButton}${r.repairPhotoCount?`🔧 ${r.repairPhotoCount} repair photo(s)`:''}<br><button class="text-button" data-action="timeline" data-report-id="${r.id}">View timeline</button> <button class="text-button" data-action="comment" data-report-id="${r.id}">Add comment</button> <button class="text-button" data-action="repair" data-report-id="${r.id}">Add repair proof</button></span><span class="status ${statusClass(r.status)}">${r.status}</span>${update}${assignment}</div>`:`<div class="report-row"><span class="report-icon">${icon}</span><div class="report-info"><strong>${escapeHtml(r.category)} <small>· ${escapeHtml(r.reference)}</small></strong><small>${escapeHtml(r.office)} · ${displayDate(r.createdAt)}</small></div><span class="status ${statusClass(r.status)}">${r.status}</span></div>`}
async function renderDashboard(){const [reportData,staffData]=await Promise.all([api('/reports'),api('/staff/officers')]);reports=reportData.reports;state.officers=staffData.officers;const count=s=>reports.filter(r=>r.status===s).length;$('#newMetric').textContent=count('New');$('#progressMetric').textContent=count('In progress');$('#resolvedMetric').textContent=count('Resolved');$('#reportCount').textContent=reports.length;$('#attentionList').innerHTML=reports.filter(r=>r.status==='New').slice(0,4).map(r=>row(r)).join('')||'<p>No reports awaiting review.</p>';renderReports();}
function renderReports(){const s=$('#statusFilter').value,c=$('#categoryFilter').value;const items=reports.filter(r=>(s==='All'||r.status===s)&&(c==='All'||r.category===c));$('#reportsList').innerHTML=items.map(r=>row(r,true)).join('')||'<p>No reports match these filters.</p>'}
$('#reportsList').addEventListener('change',e=>{if(e.target.matches('.status-update'))window.updateStatus(e.target.dataset.reportId,e.target.value);if(e.target.matches('.assignment-update'))window.assignOfficer(e.target.dataset.reportId,e.target.value);});
$('#reportsList').addEventListener('click',e=>{const button=e.target.closest('button[data-action]');if(!button)return;const id=button.dataset.reportId;if(button.dataset.action==='timeline')window.showTimeline(id);if(button.dataset.action==='comment')window.addComment(id);if(button.dataset.action==='repair')window.addRepairPhoto(id);if(button.dataset.action==='citizen-photo'){const report=reports.find(item=>item.id===id);if(report?.reporterPhotoUrl)showPhoto(report.reporterPhotoUrl,`Citizen photo · ${report.reference}`);}});
window.updateStatus=async(id,status)=>{try{await api(`/reports/${id}`,{method:'PATCH',body:JSON.stringify({status})});toast(`Report marked ${status}. The update is saved and audited.`);await renderDashboard();initMaps();}catch(error){toast(error.message);}};$('#statusFilter').onchange=renderReports;$('#categoryFilter').onchange=renderReports;
window.assignOfficer=async(id,assignedTo)=>{try{await api(`/reports/${id}`,{method:'PATCH',body:JSON.stringify({assignedTo})});toast('Officer assignment saved and recorded in the audit trail.');await renderDashboard();}catch(error){toast(error.message);}};
window.addComment=async id=>{const body=window.prompt('Add a staff-only report comment:');if(!body?.trim())return;try{await api(`/reports/${id}/comments`,{method:'POST',body:JSON.stringify({body})});toast('Comment saved to the report audit.');await renderDashboard();}catch(error){toast(error.message);}};
window.addRepairPhoto=id=>{const picker=document.createElement('input');picker.type='file';picker.accept='image/jpeg,image/png,image/webp';picker.onchange=async()=>{if(!picker.files[0])return;const data=new FormData();data.append('photos',picker.files[0]);try{await api(`/reports/${id}/repair-photos`,{method:'POST',body:data});toast('Repair evidence saved securely.');await renderDashboard();}catch(error){toast(error.message);}};picker.click();};
window.showTimeline=async id=>{try{const data=await api(`/reports/${id}/timeline`);$('#timelineTitle').textContent=`${data.reference} timeline`;$('#timelineMeta').textContent=`${data.category} · ${data.county} · Current status: ${data.status}`;$('#timelineList').innerHTML=data.events.length?data.events.map(event=>`<article class="timeline-event"><h3>${escapeHtml(event.type.replaceAll('_',' '))}</h3><p>${escapeHtml(event.detail||'No additional detail.')} · ${escapeHtml(event.actor)}</p><time>${displayDate(event.at)}</time></article>`).join(''):'<p>No timeline entries yet.</p>';$('#timelineModal').hidden=false;}catch(error){toast(error.message);}};
$('#closeTimeline').onclick=()=>$('#timelineModal').hidden=true;$('#timelineModal').onclick=e=>{if(e.target===$('#timelineModal'))$('#timelineModal').hidden=true};
function showPhoto(url,title){$('#photoTitle').textContent=title;$('#evidenceImage').src=url;$('#photoModal').hidden=false;}
$('#closePhoto').onclick=()=>{$('#photoModal').hidden=true;$('#evidenceImage').src='';};$('#photoModal').onclick=e=>{if(e.target===$('#photoModal'))$('#closePhoto').click()};
$$('.side-nav[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-tab-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.tabJump));function showTab(tab){if(['enrollment','management'].includes(tab)&&state.user?.role!=='admin'){toast('Only administrators can manage staff.');return;}$$('.side-nav[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.dash-tab').forEach(x=>x.classList.remove('active'));$('#'+tab+'Tab').classList.add('active');$('#dashTitle').textContent=tab==='overview'?`Good morning, ${state.user?.name?.split(' ')[0]||'staff member'}.`:tab==='reports'?'Report management':tab==='enrollment'?'Staff enrollment':tab==='management'?'Staff management':'Regional visibility';$('#dashSubtitle').textContent=tab==='enrollment'?'Create authorised KeRRA staff accounts.':tab==='management'?'Deactivate accounts safely or update staff access.':tab==='overview'?'Here’s what needs attention across your region.':tab==='reports'?'Review and update road defects.':'See the geographic distribution of reports.';if(tab==='management')loadStaff();setTimeout(initMaps,80)}
$('#signOutBtn').onclick=()=>{sessionStorage.removeItem('bw_token');sessionStorage.removeItem('bw_user');state.token=null;state.user=null;state.officers=[];$('#loginForm').reset();switchView('staffLogin');toast('You have signed out.');};
$('#enrollmentForm').onsubmit=async e=>{e.preventDefault();$('#enrolResult').textContent='';try{const {user}=await api('/staff/users',{method:'POST',body:JSON.stringify({name:$('#enrolName').value,email:$('#enrolEmail').value,office:$('#enrolOffice').value,role:$('#enrolRole').value,password:$('#enrolPassword').value})});$('#enrollmentForm').reset();$('#enrolResult').textContent=`Account created for ${user.name} (${user.role}).`;toast('Staff account created.');}catch(error){$('#enrolResult').textContent=error.message;}};
let managedStaff=[];
async function loadStaff(){try{const {users}=await api('/staff/users');managedStaff=users;$('#staffList').innerHTML=users.map(user=>`<div class="report-row"><span class="report-icon">${user.active?'✓':'—'}</span><div class="report-info"><strong>${escapeHtml(user.name)} <small>· ${escapeHtml(user.role)}</small></strong><small>${escapeHtml(user.email)} · ${escapeHtml(user.office)}</small></div><span class="status ${user.active?'Resolved':'New'}">${user.active?'Active':'Deactivated'}</span><button class="text-button" data-staff-action="toggle" data-staff-id="${user._id}">${user.active?'Deactivate':'Reactivate'}</button><button class="text-button" data-staff-action="role" data-staff-id="${user._id}">Role</button><button class="text-button" data-staff-action="office" data-staff-id="${user._id}">Office</button><button class="text-button" data-staff-action="password" data-staff-id="${user._id}">Reset password</button></div>`).join('')||'<p>No staff accounts found.</p>';}catch(error){toast(error.message);}}
$('#staffList').addEventListener('click',async e=>{const button=e.target.closest('button[data-staff-action]');if(!button)return;const user=managedStaff.find(item=>item._id===button.dataset.staffId);if(!user)return;const action=button.dataset.staffAction;let changes={};if(action==='toggle'){if(!confirm(`${user.active?'Deactivate':'Reactivate'} ${user.name}?`))return;changes.active=!user.active;}if(action==='role'){const role=prompt('Role: admin, coordinator, or officer',user.role);if(!role)return;changes.role=role.trim().toLowerCase();}if(action==='office'){const office=prompt('KeRRA office',user.office);if(!office)return;changes.office=office.trim();}if(action==='password'){const password=prompt('New temporary password (at least 12 characters)');if(!password)return;changes.password=password;}try{await api(`/staff/users/${user._id}`,{method:'PATCH',body:JSON.stringify(changes)});toast('Staff account updated.');loadStaff();}catch(error){toast(error.message);}});
function drawBoundaries(map){if(map._bwBoundaries)return;if(!boundaryLoad)boundaryLoad=fetch('/api/reports/boundaries').then(r=>r.ok?r.json():Promise.reject()).then(data=>(boundaryData=data,data)).catch(()=>null);boundaryLoad.then(data=>{if(!data||map._bwBoundaries)return;const features=data.features||[];map._bwBoundaries=L.geoJSON({type:'FeatureCollection',features},{style:{color:'#176b4c',weight:1.2,fillColor:'#d9ec64',fillOpacity:.08}}).addTo(map);});}
function createMapLayers(){const attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>';const voyager=L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{attribution,subdomains:'abcd',maxZoom:20});const dark=L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution,subdomains:'abcd',maxZoom:20});const terrain=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{attribution:'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="https://viewfinderpanoramas.org/">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a>',subdomains:'abc',maxZoom:17});return {voyager,dark,terrain};}
function initMaps(){if(!window.L)return;const kenyaBounds=L.latLngBounds([[-4.8,33.0],[5.3,41.9]]);const options={center:[0.4,37.9],zoom:6,zoomControl:false,maxBounds:kenyaBounds,maxBoundsViscosity:1,minZoom:5};if(!miniMap)miniMap=L.map('miniMap',options).fitBounds(kenyaBounds);if(!fullMap)fullMap=L.map('fullMap',options).fitBounds(kenyaBounds);[miniMap,fullMap].forEach(map=>{if(!map._bwTiles){const layers=createMapLayers();layers.voyager.addTo(map);map._bwTiles=layers.voyager;map._bwLayerControl=L.control.layers({'Standard View':layers.voyager,'Dark Mode':layers.dark,'Terrain Map':layers.terrain},null,{position:'topright'}).addTo(map);}drawBoundaries(map);map.eachLayer(l=>{if(l instanceof L.CircleMarker)map.removeLayer(l)});reports.forEach(r=>{if(!r.location||typeof r.location.lat!=='number'||typeof r.location.lng!=='number')return;L.circleMarker([r.location.lat,r.location.lng],{radius:8,color:'#fff',weight:2,fillColor:r.severity==='Critical'?'#d64c3b':r.status==='In progress'?'#4f83b9':'#e58032',fillOpacity:1}).addTo(map).bindPopup(`<b>${escapeHtml(r.category)}</b><br>${escapeHtml(r.reference)}<br>${escapeHtml(r.office)}<br><em>${escapeHtml(r.status)}</em>`);});map.invalidateSize()})}
function handleAuthError(error){if(/session|Authentication|expired/i.test(error.message)){sessionStorage.clear();state.token=null;state.user=null;toast('Your staff session has ended. Please sign in again.');switchView('staffLogin');}else toast(error.message)}
if(state.user){$('#staffName').textContent=state.user.name;$('#staffRole').textContent=state.user.role;$('#staffOffice').textContent=state.user.office;setStaffControls();}
