let boundaries=null;
const sourceUrl=process.env.BOUNDARY_GEOJSON_URL||'https://services1.arcgis.com/Kw7jGaBPiN3WUAmT/ArcGIS/rest/services/final_ketraco_map/FeatureServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&f=geojson&outSR=4326&resultRecordCount=100';
const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function loadBoundaries(){let lastError;for(let attempt=1;attempt<=3;attempt++){try{const response=await fetch(sourceUrl,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw new Error(`Boundary service returned ${response.status}`);const data=await response.json();if(data.type!=='FeatureCollection'||data.features?.length!==47)throw new Error('Boundary service did not return all 47 county polygons.');boundaries=data;return data;}catch(error){lastError=error;if(attempt<3)await wait(1000*attempt);}}throw lastError;}
function pointInRing([x,y],ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside;}return inside;}
function pointInPolygon(point,geometry){const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;return polygons.some(poly=>pointInRing(point,poly[0])&&!poly.slice(1).some(hole=>pointInRing(point,hole)));}
function countyName(feature){return feature.properties.County||feature.properties.COUNTY||feature.properties.county||feature.properties.NAME||feature.properties.Name;}
function routeOffice(latitude,longitude){if(!boundaries)throw Object.assign(new Error('Verified county boundaries are not loaded.'),{status:503});const match=boundaries.features.find(f=>pointInPolygon([longitude,latitude],f.geometry));if(!match)throw Object.assign(new Error('The submitted location is outside Kenya’s official county boundaries.'),{status:400});const county=countyName(match);return {county,office:`${county} Regional Office`};}
function makeReference(){return `KRR-${new Date().getFullYear()}-${Math.floor(100000+Math.random()*900000)}`;}function getBoundaries(){return boundaries;}function setBoundariesForTest(data){boundaries=data;}module.exports={loadBoundaries,routeOffice,makeReference,getBoundaries,setBoundariesForTest};
